security:
  jwt:
    issuer: Keepcalm Auth
    audience: Keepcalm
    secret: s3cretP@ssw0rd

keepcalm:
  security:
    endpoints:
      admin:
        - "/api/salary/**"
      user:
        - "/api/document/**"
      unsecured:
        - "/faketoken"
