name: FeatureCI
on:
  push:
    branches:
      - '*'

jobs:
  BuildFeature :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Semantic Version
        id: Semver
        run: |-
          chmod +x .github/semver.sh
          ./.github/semver.sh

      - name: Cache Maven Packages
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: azure-artifactory
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build package
        run: mvn --batch-mode -file kboot-jwt-spring-boot-starter/pom.xml package -Drevision=$VERSION-SNAPSHOT

      - name: Publish package
        if: ${{ env.PREVIOUS_VERSION  != env.VERSION }}
        run: mvn --batch-mode -file kboot-jwt-spring-boot-starter/pom.xml deploy -Drevision=$VERSION-SNAPSHOT -Dmaven.test.skip=true
        env:
          MAVEN_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
