name: Feature Branch

on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test Feature and Pull Request
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v2
      # Setup JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # SemVer
      - name: Semantic Version
        id: Semver
        run: |-
          chmod +x .github/semver.sh
          ./.github/semver.sh
      # Maven Package (SkipTests)
      - name: Maven Package
        run: mvn -B -f kboot-jwt-spring-boot-starter/pom.xml clean package -Drevision=$VERSION-SNAPSHOT -DskipTests
      # Maven Verify
      - name: Maven Verify
        run: mvn -B -f kboot-jwt-spring-boot-starter/pom.xml clean verify -Drevision=$VERSION-SNAPSHOT

  releaseArtifactory:
    name: Release SNAPSHOT - Artifactory
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      # SemVer
      - name: Semantic Version
        id: Semver
        run: |-
          chmod +x .github/semver.sh
          ./.github/semver.sh
      # Setup JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # SetUp Artifactory
      - name: SetUp Repository (Artifactory)
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: azure-artifactory
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      # Publish Artifactory
      - name: Publish Package (Artifactory)
        run: mvn --batch-mode -file kboot-jwt-spring-boot-starter/pom.xml deploy -Drevision=$VERSION-SNAPSHOT -Dmaven.test.skip=true
        env:
          MAVEN_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

  sonar:
    name: Test - SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      # SemVer
      - name: Semantic Version
        id: Semver
        run: |-
          chmod +x .github/semver.sh
          ./.github/semver.sh
      # Setup JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # SonarCloud
      - name: SonarCloud Scan
        run: mvn -B -f kboot-jwt-spring-boot-starter/pom.xml verify -Drevision=$VERSION-SNAPSHOT -Pcoverage,sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
